[sources.http_source]
type = "http_server"
address = "0.0.0.0:8081"
encoding = "json"


[sinks.http_sink]
type = "http"
inputs = ["http_source"]
uri = "http://localhost:8080/id/{{id}}"
encoding.codec = "json"
